/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedExpenseTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExpense"
      | "confidentialProtocolId"
      | "deleteExpense"
      | "getEncryptedExpense"
      | "getEncryptedGlobalTotal"
      | "getExpenseCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExpenseAdded" | "ExpenseDeleted" | "TotalUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExpense",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteExpense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedExpense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedGlobalTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpenseCount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addExpense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedGlobalTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpenseCount",
    data: BytesLike
  ): Result;
}

export namespace ExpenseAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    category: BigNumberish,
    timestamp: BigNumberish,
    amountHandle: BytesLike,
    index: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    category: bigint,
    timestamp: bigint,
    amountHandle: string,
    index: bigint
  ];
  export interface OutputObject {
    user: string;
    category: bigint;
    timestamp: bigint;
    amountHandle: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpenseDeletedEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    newTotalHandle: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    index: bigint,
    newTotalHandle: string
  ];
  export interface OutputObject {
    user: string;
    index: bigint;
    newTotalHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TotalUpdatedEvent {
  export type InputTuple = [user: AddressLike, newTotalHandle: BytesLike];
  export type OutputTuple = [user: string, newTotalHandle: string];
  export interface OutputObject {
    user: string;
    newTotalHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedExpenseTracker extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedExpenseTracker;
  waitForDeployment(): Promise<this>;

  interface: EncryptedExpenseTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExpense: TypedContractMethod<
    [
      category: BigNumberish,
      timestamp: BigNumberish,
      amountExt: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deleteExpense: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedExpense: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        category: bigint;
        timestamp: bigint;
        amountHandle: string;
        isDeleted: boolean;
      }
    ],
    "view"
  >;

  getEncryptedGlobalTotal: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getExpenseCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExpense"
  ): TypedContractMethod<
    [
      category: BigNumberish,
      timestamp: BigNumberish,
      amountExt: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deleteExpense"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedExpense"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, string, boolean] & {
        category: bigint;
        timestamp: bigint;
        amountHandle: string;
        isDeleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedGlobalTotal"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getExpenseCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEvent(
    key: "ExpenseAdded"
  ): TypedContractEvent<
    ExpenseAddedEvent.InputTuple,
    ExpenseAddedEvent.OutputTuple,
    ExpenseAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExpenseDeleted"
  ): TypedContractEvent<
    ExpenseDeletedEvent.InputTuple,
    ExpenseDeletedEvent.OutputTuple,
    ExpenseDeletedEvent.OutputObject
  >;
  getEvent(
    key: "TotalUpdated"
  ): TypedContractEvent<
    TotalUpdatedEvent.InputTuple,
    TotalUpdatedEvent.OutputTuple,
    TotalUpdatedEvent.OutputObject
  >;

  filters: {
    "ExpenseAdded(address,uint32,uint256,bytes32,uint256)": TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;
    ExpenseAdded: TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;

    "ExpenseDeleted(address,uint256,bytes32)": TypedContractEvent<
      ExpenseDeletedEvent.InputTuple,
      ExpenseDeletedEvent.OutputTuple,
      ExpenseDeletedEvent.OutputObject
    >;
    ExpenseDeleted: TypedContractEvent<
      ExpenseDeletedEvent.InputTuple,
      ExpenseDeletedEvent.OutputTuple,
      ExpenseDeletedEvent.OutputObject
    >;

    "TotalUpdated(address,bytes32)": TypedContractEvent<
      TotalUpdatedEvent.InputTuple,
      TotalUpdatedEvent.OutputTuple,
      TotalUpdatedEvent.OutputObject
    >;
    TotalUpdated: TypedContractEvent<
      TotalUpdatedEvent.InputTuple,
      TotalUpdatedEvent.OutputTuple,
      TotalUpdatedEvent.OutputObject
    >;
  };
}
