/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockExpenseTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExpense"
      | "deleteExpense"
      | "getEncryptedExpense"
      | "getEncryptedGlobalTotal"
      | "getExpenseCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExpenseAdded" | "ExpenseDeleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExpense",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteExpense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedExpense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedGlobalTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpenseCount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addExpense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedGlobalTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpenseCount",
    data: BytesLike
  ): Result;
}

export namespace ExpenseAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    category: BigNumberish,
    timestamp: BigNumberish,
    amount: BigNumberish,
    index: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    category: bigint,
    timestamp: bigint,
    amount: bigint,
    index: bigint
  ];
  export interface OutputObject {
    user: string;
    category: bigint;
    timestamp: bigint;
    amount: bigint;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpenseDeletedEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [user: string, index: bigint, newTotal: bigint];
  export interface OutputObject {
    user: string;
    index: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockExpenseTracker extends BaseContract {
  connect(runner?: ContractRunner | null): MockExpenseTracker;
  waitForDeployment(): Promise<this>;

  interface: MockExpenseTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExpense: TypedContractMethod<
    [category: BigNumberish, timestamp: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteExpense: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedExpense: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        category: bigint;
        timestamp: bigint;
        amount: bigint;
        isDeleted: boolean;
      }
    ],
    "view"
  >;

  getEncryptedGlobalTotal: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getExpenseCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExpense"
  ): TypedContractMethod<
    [category: BigNumberish, timestamp: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteExpense"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedExpense"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        category: bigint;
        timestamp: bigint;
        amount: bigint;
        isDeleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedGlobalTotal"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExpenseCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEvent(
    key: "ExpenseAdded"
  ): TypedContractEvent<
    ExpenseAddedEvent.InputTuple,
    ExpenseAddedEvent.OutputTuple,
    ExpenseAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExpenseDeleted"
  ): TypedContractEvent<
    ExpenseDeletedEvent.InputTuple,
    ExpenseDeletedEvent.OutputTuple,
    ExpenseDeletedEvent.OutputObject
  >;

  filters: {
    "ExpenseAdded(address,uint32,uint256,uint32,uint256)": TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;
    ExpenseAdded: TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;

    "ExpenseDeleted(address,uint256,uint32)": TypedContractEvent<
      ExpenseDeletedEvent.InputTuple,
      ExpenseDeletedEvent.OutputTuple,
      ExpenseDeletedEvent.OutputObject
    >;
    ExpenseDeleted: TypedContractEvent<
      ExpenseDeletedEvent.InputTuple,
      ExpenseDeletedEvent.OutputTuple,
      ExpenseDeletedEvent.OutputObject
    >;
  };
}
